### ISSUE TITLE
Example configurations

### ISSUE THREAD

**Issue by Megachip** [gjr80/wee_import#7]
Are there any config examples? (e.g. for cumulus csv with solar rad)

THX a lot

**Comment by gjr80** [comment]
Hi,
> Are there any config examples? (e.g. for cumulus csv with solar rad)

Not really, at the moment all that exists is the comments up front in `wee_import.conf` and `wee_import` itself. In terms or importing from a csv, `wee_import` requires 3 things:

1. a header row in the csv file with field names (they can be anything)
1. a single field per row with the date and time (formatted or unix timestamp) of the observations
1. a csv field name to weewx field name mapping in `wee_import.conf`

This is not too onerous if importing from a single csv file (which is all I have been doing so far) but is a bit of a pain if importing from, say, a series of files with month by month data (I have never used Cumulus and I gather from my quick read through the Cumulus wiki that this is in fact how Cumulus records/logs its observation data). In fact, I just noticed that the Cumulus monthly log files use seperate date and time fields so importing with `wee_import` (as it stands now) would require some massaging of these fields to give a combined date and time field.

That being said, having put together the basic import functionality it is a fairly simple process to extend this for particular cases (this was always the plan and is exactly how the WeatherUnderground import was implemented). I am more than happy to sit down and do this for Cumulus csv data, at first glance the extra code does not look too onerous, hopefully only a few days. Could you confirm for me though that the files you wish to import are in fact the monthly log files detailed [here](http://wiki.sandaysoft.com/a/Monthly_log_files)?

Gary

**Comment by gjr80** [comment]
If you are still interested I have started a 'cumulus' branch that includes support for importing data from Cumulus monthly log files. I need to do some more testing to verify its operation and a bit of tidying up of the code and it should be good to try. Hopefully another couple of days only.

**Comment by gjr80** [comment]
You can find a version of wee_import that supports importing from Cumulus monthly log files in the release section https://github.com/gjr80/wee_import/releases. You will find a few notes on importing Cumulus data at the start of the `[Cumulus]` section in `wee_import.conf`.

To use it:

1. download the release and extract the files.
1. copy `wee_import` to the symbollic folder `BIN_ROOT` (nominally `/home/weewx/bin` or `/usr/share/weewx` depending on the weewx installation type)
1. copy `wee_import.conf` to the symbollic folder `CONFIG_ROOT` (nominally `/home/weewx` or `/etc/weewx` depending on the weewx installation type)
1. edit `wee_import.conf` and change any settings under `[Cumulus]` as required. The following settings should be changed to suit:

    - **interval**. Recommend this be set to the 'data log interval' used in Cumulus.
    - **delimiter**. Needs to be set to the field delimiter used in your monthly log files.
    - **decimal**. Needs to be set to the decimal point character used in your monthly log files.
    - `**[[Units]]**`. Need to be set to the units used in your Cumulus monthly logs. The settings need to be the weewx equivalent of the Cumulus units used (eg for Cumulus 'C' use weewx 'degree_C', the possible units are listed, they are self evident)

1. save `wee_import.conf`
1. copy your Cumulus log files to a folder accessible by your machine running weewx.
1. if you have data in weewx that you wish to retain it may be worth while stopping weewx and moving your database aside in case the import does not go as planned. Af the very least make a backup copy of your existing weewx data if you have any.
1. run `wee_import` using the command:
    
    `$ wee_import`

1. this should display the `wee_import` help. Now run `wee_import` with the `--cumulus` command line option. Something like:

    `$ wee_import --cumulus --source=/var/tmp/cumulus --calc-missing --dry-run`

    this will run `wee_import` and import all Cumulus monthly log files that reside in the `var/tmp/cumulus` folder. Any derived observations will be calculated but nothing will be saved to archive.
   
    Note that you could also use the `--date` option to limit the data being imported to certain time span.

1. if this appears to work successfully run the command again without the `--dry-run` option. This should see data imported into the weewx archive.
1. if weewx was stopped then start weewx again

Let me know if any issues.

**Comment by gjr80** [comment]
Nothing more heard. Cumulus monthly log import implemented and appears to be working correctly. Example config is included in wee_import.conf and in the comments at the start of wee_import.
